from flask_restful import Resource, fields, reqparse, marshal_with
from flask import current_app
import json
import os

# TODO investigate use of Pydantic for data validation and maintaining schema



class Grid(Resource):
    """
    Handles all logic for servicing grid data requests and updating grid data model.
    """
    def get(self, region):
        """
        Return watts generated by fuel type over a given timeseries (WIP).
        """
        return {"region": region, "data": self.__create_mock_payload()}
        
    # Testing purposes only
    def __create_mock_payload(self):
        """
        Helper function for testing purposes. Loads and returns sample JSON taken from EIA grid data.
        """
        with open(os.path.join(current_app.instance_path, 'mock_raw_grid_data.json')) as json_file:
            mock_payload = json.load(json_file)
        return mock_payload